### ISSUE TITLE
Your App Bundle targets the following unrecognized languages: gr.

### ISSUE THREAD

**Issue by nabin304** [trinnguyen/xamarin-bindings#5]
When I try to publish an app on Google Play store, which reference this library (Xamarin.RateThisApp v1.2.0) does not work. 

Details error message:
Your App Bundle targets the following unrecognized languages: gr. The list of supported language codes can be found in the IANA registry. 
Invalid languages caused by third-party libraries can be excluded using the resConfigs Gradle property.

**Comment by trinnguyen** [comment]
Add this MSBuild property to your Xamarin.Android `.csproj` would solve the issue, assume that your project use a single "en" resource set. 

```
<AndroidAapt2LinkExtraArgs>-c en</AndroidAapt2LinkExtraArgs>
```

You can add more configurations after "-c" arguments. They will be passed to `aapt2` cmd as extra arguments. In case of using `aapt`, use this property instead: AndroidResgenExtraArgs 

The reason behind this is that the native RateThisApp library has translation strings for many configurations including "gr". They are all packed together into the AppBundle package. This extras arguments make sure only some configurations are added, hence prevents the rejection error.

**Comment by nabin304** [comment]
Thanks a lot, it worked.
